### ISSUE TITLE
Catalyst crashes on GDAX when holding several positions

### ISSUE THREAD

**Issue by sam31415** [enigmampc/catalyst#326] opened 2018-05-06 20:40 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 7
* Python Version: 3.6.2
* Python Bitness: Get an error message...
* How did you install Catalyst: conda
* Python packages:
# Name                    Version                   Build  Channel
aiodns                    1.1.1                     <pip>
aiohttp                   3.0.1                     <pip>
alembic                   0.9.9                     <pip>
async-timeout             2.0.1                     <pip>
attrdict                  2.0.0                     <pip>
attrs                     17.4.0                    <pip>
backcall                  0.1.0                     <pip>
bcolz                     0.12.1                    <pip>
bleach                    2.1.3                     <pip>
boto3                     1.6.16                    <pip>
botocore                  1.9.16                    <pip>
Bottleneck                1.2.1                     <pip>
cchardet                  2.1.1                     <pip>
ccxt                      1.13.38                   <pip>
certifi                   2018.1.18                 <pip>
certifi                   2016.2.28                py36_0
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
colorama                  0.3.9                     <pip>
configparser              3.5.0                     <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.28.1                    <pip>
cytoolz                   0.9.0.1                   <pip>
decorator                 4.2.1                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.5.9                     <pip>
entrypoints               0.2.3                     <pip>
eth-abi                   1.0.0                     <pip>
eth-account               0.1.0a2                   <pip>
eth-hash                  0.1.1                     <pip>
eth-keyfile               0.5.1                     <pip>
eth-keys                  0.2.0b3                   <pip>
eth-rlp                   0.1.0                     <pip>
eth-utils                 1.0.1                     <pip>
hexbytes                  0.1.0                     <pip>
html5lib                  1.0.1                     <pip>
idna                      2.6                       <pip>
idna-ssl                  1.0.1                     <pip>
intervaltree              2.1.0                     <pip>
ipykernel                 4.8.2                     <pip>
ipython                   6.3.1                     <pip>
ipython-genutils          0.2.0                     <pip>
ipywidgets                7.2.0                     <pip>
jedi                      0.11.1                    <pip>
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
jsonschema                2.6.0                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            5.2.3                     <pip>
jupyter-console           5.2.0                     <pip>
jupyter-core              4.4.0                     <pip>
kiwisolver                1.0.1                     <pip>
Logbook                   1.3.0                     <pip>
lru-dict                  1.1.6                     <pip>
lxml                      4.2.1                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.2.2                     <pip>
mistune                   0.8.3                     <pip>
mkl                       2017.0.3                      0
mpld3                     0.3                       <pip>
multidict                 4.1.0                     <pip>
multipledispatch          0.5.0                     <pip>
nbconvert                 5.3.1                     <pip>
nbformat                  4.4.0                     <pip>
networkx                  2.1                       <pip>
notebook                  5.4.1                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.13.1                   py36_0
pandas                    0.19.2                    <pip>
pandas                    0.20.3                   py36_0
pandas-datareader         0.6.0                     <pip>
pandocfilters             1.4.2                     <pip>
parso                     0.1.1                     <pip>
patsy                     0.5.0                     <pip>
patsy                     0.4.1                    py36_0
pickleshare               0.7.4                     <pip>
pip                       10.0.1                    <pip>
pip                       9.0.1                    py36_1
prompt-toolkit            1.0.15                    <pip>
pycares                   2.3.0                     <pip>
pycryptodome              3.5.1                     <pip>
Pygments                  2.2.0                     <pip>
pyparsing                 2.2.0                     <pip>
python                    3.6.2                         0
python-dateutil           2.7.1                     <pip>
python-dateutil           2.6.1                    py36_0
python-editor             1.0.3                     <pip>
pytz                      2017.2                   py36_0
pytz                      2018.3                    <pip>
pywinpty                  0.5.1                     <pip>
pyzmq                     17.0.0                    <pip>
qtconsole                 4.3.1                     <pip>
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.8.0                     <pip>
rlp                       0.6.0                     <pip>
s3transfer                0.1.13                    <pip>
schedule                  0.5.0                     <pip>
scipy                     0.19.1              np113py36_0
Send2Trash                1.5.0                     <pip>
setuptools                36.4.0                   py36_1
simplegeneric             0.8.1                     <pip>
six                       1.10.0                   py36_0
six                       1.11.0                    <pip>
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.5                     <pip>
statsmodels               0.8.0               np113py36_0
tables                    3.4.2                     <pip>
tabulate                  0.8.2                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1                     <pip>
toolz                     0.9.0                     <pip>
tornado                   5.0.2                     <pip>
traitlets                 4.3.2                     <pip>
urllib3                   1.22                      <pip>
vc                        14                            0
vs2015_runtime            14.0.25420                    0
wcwidth                   0.1.7                     <pip>
web3                      4.0.0b11                  <pip>
webencodings              0.5.1                     <pip>
wheel                     0.29.0                   py36_0
widgetsnbextension        3.2.0                     <pip>
wincertstore              0.2                      py36_0
wrapt                     1.10.11                   <pip>
yarl                      1.1.0                     <pip>
zlib                      1.2.11                   vc14_0  [vc14]

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

When holding several positions on GDAX, the algorithm crashes with the following error message.
```
[2018-05-05 23:03:07.166919] WARNING: CCXT: unable to fetch tickers gdax / ['BCH/USD', 'LTC/USD', 'ETH/USD', 'BTC/USD']:
 gdax API does not allow to fetch all tickers at once with a single call to fetch_tickers() for now
[2018-05-05 23:03:13.167262] WARNING: CCXT: unable to fetch tickers gdax / ['BCH/USD', 'LTC/USD', 'ETH/USD', 'BTC/USD']:
 gdax API does not allow to fetch all tickers at once with a single call to fetch_tickers() for now
[2018-05-05 23:03:20.668692] WARNING: CCXT: unable to fetch tickers gdax / ['BCH/USD', 'LTC/USD', 'ETH/USD', 'BTC/USD']:
 gdax API does not allow to fetch all tickers at once with a single call to fetch_tickers() for now
[2018-05-05 23:03:31.920335] WARNING: CCXT: unable to fetch tickers gdax / ['BCH/USD', 'LTC/USD', 'ETH/USD', 'BTC/USD']:
 gdax API does not allow to fetch all tickers at once with a single call to fetch_tickers() for now
[2018-05-05 23:03:49.796358] WARNING: CCXT: unable to fetch tickers gdax / ['BCH/USD', 'LTC/USD', 'ETH/USD', 'BTC/USD']:
 gdax API does not allow to fetch all tickers at once with a single call to fetch_tickers() for now
Traceback (most recent call last):
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\exchange\ccxt\ccxt_exchange.py", line 1052, in
tickers
    results = self.api.fetch_tickers(symbols=symbols)
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\ccxt\base\exchange.py", line 942, in fetch_tickers
    self.raise_error(NotSupported, details='API does not allow to fetch all tickers at once with a single call to fetch_tickers() for now')
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\ccxt\base\exchange.py", line 288, in raise_error
    raise exception_type(output)
ccxt.base.errors.NotSupported: gdax API does not allow to fetch all tickers at once with a single call to fetch_tickers(
) for now

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "algo.py", line 882, in <module>
    simulate_orders = PAPER_TRADE,
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\utils\run_algo.py", line 584, in run_algorithm
    stats_output=stats_output
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\utils\run_algo.py", line 348, in _run
    overwrite_sim_params=False,
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 1044, in run
    data, overwrite_sim_params
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 358, in run
    data, overwrite_sim_params
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\gens\tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\gens\tradesimulation.py", line 137, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\utils\events.py", line 216, in handle_data
    dt,
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\utils\events.py", line 235, in handle_data
    self.callback(context, data)
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 890, in handle_data
    cleanup=lambda: log.warn('Ordering again.')
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\redo\__init__.py", line 162, in retry
    return action(*args, **kwargs)
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\exchange\exchange_algorithm.py", line 713, in synchronize_portfolio
    cash=required_cash,
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\exchange\exchange.py", line 725, in sync_positions
    tickers = self.tickers(assets)
  File "C:\Users\User\Anaconda2\envs\catalyst3\lib\site-packages\catalyst\exchange\ccxt\ccxt_exchange.py", line 1060, in tickers
    raise ExchangeRequestError(error=e)
catalyst.exchange.exchange_errors.ExchangeRequestError: Request failed: gdax API does not allow to fetch all tickers at once with a single call to fetch_tickers() for now
```

It's a bit strange, because I don't have trouble fetching price data for several pairs at once. Maybe Catalysts handles correctly the calls to data.current and data.history by breaking them pair by pair, but somehow doesn't do this for some other calls? It doesn't look like this call is coming directly from my algorithm, so I can't really do much about it.

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. Have an algorithm open several positions on GDAX.
2. This should be sufficient to get the error above.

Sincerely,
Samuel

**Comment by lenak25** [comment] 2018-05-07 08:36
Thanks @sam31415 , it is a duplicate of #299.
I am closing this, let's continue this discussion on that thread.

**Closed by lenak25** 2018-05-07 08:36 UTC
