### ISSUE TITLE
Issues when using ingest

### ISSUE THREAD

**Issue by riopal** [enigmampc/catalyst#48] opened 2017-10-30 17:25 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows 10)
* Python Version: `$ 2.7`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
Now I keep on getting this and im unnable to run the test strategy

(catalyst) C:\Users\user C-137>catalyst ingest
Traceback (most recent call last):
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\user C-137\AppData\Local\conda\conda\envs\catalyst\Scripts\catalyst.exe\__main__.py", line 5, in <module>
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\__init__.py", line 25, in <module>
    from .utils.run_algo import run_algorithm
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\utils\run_algo.py", line 11, in <module>
    from catalyst.exchange.bittrex.bittrex import Bittrex
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\exchange\bittrex\bittrex.py", line 11, in <module>
    from catalyst.exchange.exchange import Exchange
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\exchange\exchange.py", line 13, in <module>
    from catalyst.data.data_portal import BASE_FIELDS
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\data\data_portal.py", line 47, in <module>
    from catalyst.data.resample import (
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\data\resample.py", line 29, in <module>
    from catalyst.data.minute_bars import MinuteBarReader
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\catalyst\data\minute_bars.py", line 29, in <module>
    import tables
  File "c:\users\user c-137\appdata\local\conda\conda\envs\catalyst\lib\site-packages\tables\__init__.py", line 74, in <module>
    ' that it can be found in the system path' % hdf5_dlls)
ImportError: Could not load any of ['hdf5.dll', 'hdf5dll.dll'], please ensure that it can be found in the system path

(catalyst) C:\Users\user C-137>

**Comment by lacabra** [comment] 2017-10-30 17:28
`catalyst ingest` is deprecated. Use instead `catalyst ingest-exchange -x {exchange_name}`. For up-to-date instructions see https://enigmampc.github.io/catalyst/beginner-tutorial.html

**Comment by riopal** [comment] 2017-10-30 18:16
Hey I just tried it doest work either I get the same error.

**Comment by lacabra** [comment] 2017-10-30 20:35
ok, so run `catalyst ingest-exchange -x bitfinex` and post here the full trace of the error. It must be something specific to your installation in Windows. Happy to help troubleshoot.

**Comment by lacabra** [comment] 2017-10-31 06:14
You didn't say that your first conda install failed, and you created the environment manually. I figured this out troubleshooting another install that experienced the same issue. When you created the environment with this command:
`conda create --name catalyst python=2.7 scipy`
you should use instead:
`conda create --name catalyst python=2.7 scipy zlib`
I have updated the documentation available at [https://enigmampc.github.io/catalyst/install.html#troubleshooting-conda-install](https://enigmampc.github.io/catalyst/install.html#troubleshooting-conda-install) accordingly.

In order to do the change above, you will probably need to remove the catalyst environment that is not working by running the following command first:
`conda remove --name catalyst --all`

Let me know if this fixes your issue.

**Comment by riopal** [comment] 2017-10-31 12:49
Hey,
Unfortunately it did not solve my problem :/

Here is the code. However you are right over the instalation code I used the troubleshooter.
(C:\ana) C:\Users\user C-137>conda remove --name catalyst --all

Package plan for package removal in environment C:\ana\envs\catalyst:

The following packages will be REMOVED:

    certifi:        2017.7.27.1-py27hf761292_0
    icc_rt:         2017.0.4-h97af966_0
    intel-openmp:   2018.0.0-hcd89f80_7
    mkl:            2018.0.0-h36b65af_4
    numpy:          1.13.3-py27h9ac254c_0
    pip:            9.0.1-py27hdaa76b4_4
    python:         2.7.14-h4084c39_22
    scipy:          0.19.1-py27h069396b_3
    setuptools:     36.5.0-py27ha483b79_0
    vc:             9-h7299396_1
    vs2008_runtime: 9.00.30729.1-hfaea7d5_1
    wheel:          0.29.0-py27hffb40b6_1
    wincertstore:   0.2-py27hf04cefb_0

Proceed ([y]/n)? y


(C:\ana) C:\Users\user C-137>
(C:\ana) C:\Users\user C-137>conda remove --name catalyst --all

Package plan for package removal in environment C:\Users\user C-137\AppData\Local\conda\conda\envs\catalyst:

The following packages will be REMOVED:

    certifi:        2017.7.27.1-py27hf761292_0
    icc_rt:         2017.0.4-h97af966_0
    intel-openmp:   2018.0.0-hcd89f80_7
    mkl:            2018.0.0-h36b65af_4
    numpy:          1.13.3-py27h9ac254c_0
    pip:            9.0.1-py27hdaa76b4_4
    python:         2.7.14-h4084c39_22
    scipy:          0.19.1-py27h069396b_3
    setuptools:     36.5.0-py27ha483b79_0
    vc:             9-h7299396_1
    vs2008_runtime: 9.00.30729.1-hfaea7d5_1
    wheel:          0.29.0-py27hffb40b6_1
    wincertstore:   0.2-py27hf04cefb_0

Proceed ([y]/n)?


(C:\ana) C:\Users\user C-137>y
'y' is not recognized as an internal or external command,
operable program or batch file.

(C:\ana) C:\Users\user C-137>conda remove --name catalyst --all

CondaEnvironmentNotFoundError: Could not find environment: catalyst .
You can list all discoverable environments with `conda info --envs`.


(C:\ana) C:\Users\user C-137>conda create --name catalyst python=2.7 scipy zlib
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\ana\envs\catalyst:

The following NEW packages will be INSTALLED:

    certifi:        2017.7.27.1-py27hf761292_0
    icc_rt:         2017.0.4-h97af966_0
    intel-openmp:   2018.0.0-hcd89f80_7
    mkl:            2018.0.0-h36b65af_4
    numpy:          1.13.3-py27h9ac254c_0
    pip:            9.0.1-py27hdaa76b4_4
    python:         2.7.14-h4084c39_22
    scipy:          0.19.1-py27h069396b_3
    setuptools:     36.5.0-py27ha483b79_0
    vc:             9-h7299396_1
    vs2008_runtime: 9.00.30729.1-hfaea7d5_1
    wheel:          0.29.0-py27hffb40b6_1
    wincertstore:   0.2-py27hf04cefb_0
    zlib:           1.2.11-vc9ha80f4e8_1       [vc9]

Proceed ([y]/n)? y

zlib-1.2.11-vc 100% |###############################| Time: 0:00:05  20.79 kB/s
#
# To activate this environment, use:
# > activate catalyst
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


(C:\ana) C:\Users\user C-137>activate catalyst

(catalyst) C:\Users\user C-137>pip install enigma-catalyst matplotlib
Collecting enigma-catalyst
Collecting matplotlib
  Using cached matplotlib-2.1.0-cp27-cp27m-win_amd64.whl
Collecting requests-file>=1.4.1 (from enigma-catalyst)
Collecting cyordereddict>=0.2.2 (from enigma-catalyst)
Requirement already satisfied: numpy>=1.13.1 in c:\ana\envs\catalyst\lib\site-packages (from enigma-catalyst)
Collecting six>=1.10.0 (from enigma-catalyst)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting requests>=2.9.1 (from enigma-catalyst)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting decorator>=4.0.0 (from enigma-catalyst)
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting Cython>=0.25.2 (from enigma-catalyst)
  Using cached Cython-0.27.2-cp27-cp27m-win_amd64.whl
Collecting lru-dict>=1.1.4 (from enigma-catalyst)
Collecting bcolz<1,>=0.12.1 (from enigma-catalyst)
Collecting MarkupSafe>=0.23 (from enigma-catalyst)
Collecting pandas<0.20,>=0.19.2 (from enigma-catalyst)
  Using cached pandas-0.19.2-cp27-cp27m-win_amd64.whl
Collecting empyrical<0.2.2,>=0.2.1 (from enigma-catalyst)
Collecting bottleneck>=1.0.0 (from enigma-catalyst)
Collecting numexpr>=2.6.1 (from enigma-catalyst)
  Using cached numexpr-2.6.4-cp27-none-win_amd64.whl
Collecting toolz>=0.8.2 (from enigma-catalyst)
Requirement already satisfied: scipy>=0.17.1 in c:\ana\envs\catalyst\lib\site-packages (from enigma-catalyst)
Collecting sqlalchemy>=1.0.8 (from enigma-catalyst)
Collecting contextlib2>=0.4.0 (from enigma-catalyst)
  Using cached contextlib2-0.5.5-py2.py3-none-any.whl
Collecting python-dateutil>=2.4.2 (from enigma-catalyst)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting tables>=3.3.0 (from enigma-catalyst)
  Using cached tables-3.4.2-cp27-cp27m-win_amd64.whl
Requirement already satisfied: setuptools>36.0 in c:\ana\envs\catalyst\lib\site-packages (from enigma-catalyst)
Collecting pytz>=2016.4 (from enigma-catalyst)
  Using cached pytz-2017.3-py2.py3-none-any.whl
Collecting patsy>=0.4.0 (from enigma-catalyst)
  Using cached patsy-0.4.1-py2.py3-none-any.whl
Collecting statsmodels>=0.6.1 (from enigma-catalyst)
Collecting networkx>=1.9.1 (from enigma-catalyst)
Collecting multipledispatch>=0.4.8 (from enigma-catalyst)
  Using cached multipledispatch-0.4.9-py2.py3-none-any.whl
Collecting pandas-datareader>=0.2.1 (from enigma-catalyst)
  Using cached pandas_datareader-0.5.0-py2.py3-none-any.whl
Collecting Logbook>=0.12.5 (from enigma-catalyst)
  Using cached Logbook-1.1.0-cp27-cp27m-win_amd64.whl
Collecting sortedcontainers>=1.4.4 (from enigma-catalyst)
  Using cached sortedcontainers-1.5.7-py2.py3-none-any.whl
Requirement already satisfied: pip>=7.1.0 in c:\ana\envs\catalyst\lib\site-packages (from enigma-catalyst)
Collecting intervaltree>=2.1.0 (from enigma-catalyst)
Collecting click>=4.0.0 (from enigma-catalyst)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting alembic>=0.7.7 (from enigma-catalyst)
Collecting Mako>=1.0.1 (from enigma-catalyst)
Collecting backports.functools-lru-cache (from matplotlib)
  Using cached backports.functools_lru_cache-1.4-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.9.1->enigma-catalyst)
 Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests>=2.9.1->enigma-catalyst)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.9.1->enigma-catalyst)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in c:\ana\envs\catalyst\lib\site-packages (from requests>=2.9.1->enigma-catalyst)
Collecting requests-ftp (from pandas-datareader>=0.2.1->enigma-catalyst)
Collecting python-editor>=0.3 (from alembic>=0.7.7->enigma-catalyst)
Installing collected packages: urllib3, idna, chardet, requests, six, requests-file, cyordereddict, decorator, Cython, lru-dict, bcolz, MarkupSafe, pytz, python-dateutil, pandas, bottleneck, empyrical, numexpr, toolz, sqlalchemy, contextlib2, tables, patsy, statsmodels, networkx, multipledispatch, requests-ftp, pandas-datareader, Logbook, sortedcontainers, intervaltree, click, python-editor, Mako, alembic, enigma-catalyst, backports.functools-lru-cache, cycler, pyparsing, matplotlib
Successfully installed Cython-0.27.2 Logbook-1.1.0 Mako-1.0.7 MarkupSafe-1.0 alembic-0.9.6 backports.functools-lru-cache-1.4 bcolz-0.12.1 bottleneck-1.2.1 chardet-3.0.4 click-6.7 contextlib2-0.5.5 cycler-0.10.0 cyordereddict-1.0.0 decorator-4.1.2 empyrical-0.2.1 enigma-catalyst-0.3.3 idna-2.6 intervaltree-2.1.0 lru-dict-1.1.6 matplotlib-2.1.0 multipledispatch-0.4.9 networkx-2.0 numexpr-2.6.4 pandas-0.19.2 pandas-datareader-0.5.0 patsy-0.4.1 pyparsing-2.2.0 python-dateutil-2.6.1 python-editor-1.0.3 pytz-2017.3 requests-2.18.4 requests-file-1.4.2 requests-ftp-0.3.1 six-1.11.0 sortedcontainers-1.5.7 sqlalchemy-1.1.14 statsmodels-0.8.0 tables-3.4.2 toolz-0.8.2 urllib3-1.22

(catalyst) C:\Users\user C-137>
(catalyst) C:\Users\user C-137>catalyst ingest
Error: No bundle registered with the name None

(catalyst) C:\Users\user C-137>

































Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: Victor <notifications@github.com>
Verzonden: Tuesday, October 31, 2017 7:14:20 AM
Aan: enigmampc/catalyst
CC: riopal; Author
Onderwerp: Re: [enigmampc/catalyst] Issues when using ingest (#48)


You didn't say that your first conda install failed, and you created the environment manually. I figured this out troubleshooting another install that experienced the same issue. When you created the environment with this command:
conda create --name catalyst python=2.7 scipy
you should use instead:
conda create --name catalyst python=2.7 scipy zlib
I have updated the documentation available at https://enigmampc.github.io/catalyst/install.html#troubleshooting-conda-install accordingly.

In order to do the change above, you will probably need to remove the catalyst environment that is not working by running the following command first:
conda remove --name catalyst --all

Let me know if this fixes your issue.

**Comment by lacabra** [comment] 2017-10-31 15:10
Hi @riopal,
You were experiencing two different issues, and the instructions above solved your first issue. Let me review:
- Your first issue is that catalyst was not properly installed, and the corresponding error message `ImportError: Could not load any of ['hdf5.dll', 'hdf5dll.dll'], please ensure that it can be found in the system path` was the sign that catalyst was not properly installed and missing some libraries. What you last did fixed the installation, because this message went away.
- Now that you have Catalyst properly installed, refer to my initial message:

> catalyst ingest is deprecated. Use instead catalyst ingest-exchange -x {exchange_name}. For up-to-date instructions see https://enigmampc.github.io/catalyst/beginner-tutorial.html

Which will fix both issues.

I am closing this issue because the installation issue has been resolved (and the documentation updated accordingly) and what you see now is expected behavior as the command `catalyst ingest` is deprecated. Please refer to the most up to date documentation.

Thank you.

**Closed** 2017-10-31 15:11 UTC
