### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by DASHsekar** [enigmampc/catalyst#232] opened 2018-02-13 08:36 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version 8.1.pro`)
* Python Version: `2.7`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`)
* Python packages: `$ pip freeze` 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

*i'm running mininet/examples/miniedit.py in MIninet
i received this issue.

MiniEdit running against Mininet 2.2.2
Traceback (most recent call last):
File "mininet/examples/miniedit.py", line 3579, in
app = MiniEdit()
File "mininet/examples/miniedit.py", line 1110, in init
Frame.init( self, parent )
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2537, in init
Widget.init(self, master, 'frame', cnf, {}, extra)
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2049, in init
BaseWidget._setup(self, master, cnf)
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2024, in _setup
_default_root = Tk()
File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in init
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

Sincerely,
`sekar

Sincerely,
sekar

**Comment by lacabra** [comment] 2018-02-13 17:11
Duplicate of #231. Closing this in favor of the former.

**Closed by lacabra** 2018-02-13 17:11 UTC
