### ISSUE TITLE
[question] context.portfolio.positions is empty.

### ISSUE THREAD

**Issue by ripley** [enigmampc/catalyst#510] opened 2018-11-13 15:43 UTC
Dear Catalyst Maintainers,

I think this is more a question instead of an issue. If it's really a problem I think it should have been opened long ago.

I created a very simple test strategy to try out the framework, as below:

`from catalyst import run_algorithm
from catalyst.api import order, record, symbol

def initialize(context):
    context.asset = symbol('bch_usd')

def handle_data(context, data):
    ... ...
    record(btc=data.current(context.asset, 'price'))

if __name__ == '__main__':
    run_algorithm(
        capital_base=101,
        initialize=initialize,
        handle_data=handle_data,
        exchange_name='bitfinex',
        live=True,
        simulate_orders=False,
        algo_namespace='my_algo_name',
        quote_currency='usd'
    )`

Given I already have some position on BCH/USDT, I was expecting in handle_data the context.portfolio.positions should contains that position, however I always end up with an empty dict for that variable.

The position was initiated by myself manually, I'm suspecting if that is the reason it's not tracked by catalyst.
Could you please confirm ? or kindly suggest what I might have done wrong.

I can get the position directly with bitfinex API v2 as:

In [38]: pos = ex2.private_post_auth_r_positions()
In [39]: pos
Out[39]:
[['tBCHUSD',
  'ACTIVE',
  -30.50597163,
  543.92676566,
  -0.01776972,
  0,
  225.31178805,
  1.35787134,
  624.46843668,
  -3.2016]]

Thanks.

**Comment by FWangTrading** [comment] 2018-11-16 05:17
according to https://enigma.co/catalyst/status/#Bitfinex, only bch_usd (no t) is supported on Bitfinex

**Comment by lenak25** [comment] 2018-11-18 10:31
@ripley , this question has been raised several times already (#480, #185).

By design, the algorithm should not have the ability to impact the orders/positions that were not performed by it. 
When starting a new strategy, its parameters - like quote currency and capital base - define the strategy boundaries, meaning that any existing position you might have, should not be disrupted by your algorithm decisions.

Closing this, feel free to reopen if you feel otherwise.

**Closed by lenak25** 2018-11-18 10:31 UTC
