### ISSUE TITLE
Running my first algorithm "UnsupportedOperation: not writable" and other errors

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#261] opened 2018-02-28 10:14 UTC
Hi,

I've been trying to run my first basic algorithm using pycharm Jupyter notebook on windows 10.
I followed the instructions in this page - https://enigmampc.github.io/catalyst/beginner-tutorial.html
(section that starts with the title "Running Algorithms")

when running the cell magic part (%%catalyst) I get the following error:

[2018-02-28 10:08:20.108635] WARNING: run_algo: Catalyst is currently in ALPHA. It is going through rapid development and it is subject to errors. Please use carefully. We encourage you to report any issue on GitHub: https://github.com/enigmampc/catalyst/issues
[2018-02-28 10:08:23.112193] INFO: run_algo: running algo in backtest mode
[2018-02-28 10:08:23.116200] INFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2017-06-27 00:00:00+00:00, updating the bundles.
---------------------------------------------------------------------------
PricingDataNotLoadedError                 Traceback (most recent call last)
C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\exchange\exchange_bundle.py in get_history_window_series_and_load(self, assets, end_dt, bar_count, field, data_frequency, algo_end_dt, force_auto_ingest)
    858                     field=field,
--> 859                     data_frequency=data_frequency,
    860                 )

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\exchange\exchange_bundle.py in get_history_window_series(self, assets, end_dt, bar_count, field, data_frequency, reset_reader)
   1004                     start_dt=asset_start_dt,
-> 1005                     end_dt=end_dt
   1006                 )

PricingDataNotLoadedError: Missing data for bitfinex btc_usd in date range [2015-03-02 00:00:00+00:00 - 2017-06-27 00:00:00+00:00]
Please run: `catalyst ingest-exchange -x bitfinex -f daily -i btc_usd`. See catalyst documentation for details.

During handling of the above exception, another exception occurred:

UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-8-72a277accfc1> in <module>()
----> 1 get_ipython().run_cell_magic('catalyst', '--start 2017-3-2 --end 2017-6-28 --capital-base 100000 -x bitfinex -c usd', "\nfrom catalyst.finance.slippage import VolumeShareSlippage\n\nfrom catalyst.api import (\n    order_target_value,\n    symbol,\n    record,\n    cancel_order,\n    get_open_orders,\n)\n\ndef initialize(context):\n    context.ASSET_NAME = 'btc_usd'\n    context.TARGET_HODL_RATIO = 0.8\n    context.RESERVE_RATIO = 1.0 - context.TARGET_HODL_RATIO\n\n    # For all trading pairs in the poloniex bundle, the default denomination\n    # currently supported by Catalyst is 1/1000th of a full coin. Use this\n    # constant to scale the price of up to that of a full coin if desired.\n    context.TICK_SIZE = 1000.0\n\n    context.is_buying = True\n    context.asset = symbol(context.ASSET_NAME)\n\n    context.i = 0\n\ndef handle_data(context, data):\n    context.i += 1\n\n    starting_cash = context.portfolio.starting_cash\n    target_hodl_value = context.TARGET_HODL_RATIO * starting_cash\n    reserve_value = context.RESERVE_RATIO * starting_cash\n\n    # Cancel any outstanding orders\n    orders = get_open_orders(context.asset) or []\n    for order in orders:\n        cancel_order(order)\n\n    # Stop buying after passing the reserve threshold\n    cash = context.portfolio.cash\n    if cash <= reserve_value:\n        context.is_buying = False\n\n    # Retrieve current asset price from pricing data\n    price = data.current(context.asset, 'price')\n\n    # Check if still buying and could (approximately) afford another purchase\n    if context.is_buying and cash > price:\n        # Place order to make position in asset equal to target_hodl_value\n        order_target_value(\n            context.asset,\n            target_hodl_value,\n            limit_price=price*1.1,\n        )\n\n    record(\n        price=price,\n        volume=data.current(context.asset, 'volume'),\n        cash=cash,\n        starting_cash=context.portfolio.starting_cash,\n        leverage=context.account.leverage,\n    )\n\ndef analyze(context=None, results=None):\n    import matplotlib.pyplot as plt\n\n    # Plot the portfolio and asset data.\n    ax1 = plt.subplot(611)\n    results[['portfolio_value']].plot(ax=ax1)\n    ax1.set_ylabel('Portfolio Value (USD)')\n\n    ax2 = plt.subplot(612, sharex=ax1)\n    ax2.set_ylabel('{asset} (USD)'.format(asset=context.ASSET_NAME))\n    (context.TICK_SIZE * results[['price']]).plot(ax=ax2)\n\n    trans = results.ix[[t != [] for t in results.transactions]]\n    buys = trans.ix[\n        [t[0]['amount'] > 0 for t in trans.transactions]\n    ]\n    ax2.plot(\n        buys.index,\n        context.TICK_SIZE * results.price[buys.index],\n        '^',\n        markersize=10,\n        color='g',\n    )\n\n    ax3 = plt.subplot(613, sharex=ax1)\n    results[['leverage', 'alpha', 'beta']].plot(ax=ax3)\n    ax3.set_ylabel('Leverage ')\n\n    ax4 = plt.subplot(614, sharex=ax1)\n    results[['starting_cash', 'cash']].plot(ax=ax4)\n    ax4.set_ylabel('Cash (USD)')\n\n    results[[\n        'treasury',\n        'algorithm',\n        'benchmark',\n    ]] = results[[\n        'treasury_period_return',\n        'algorithm_period_return',\n        'benchmark_period_return',\n    ]]\n\n    ax5 = plt.subplot(615, sharex=ax1)\n    results[[\n        'treasury',\n        'algorithm',\n        'benchmark',\n    ]].plot(ax=ax5)\n    ax5.set_ylabel('Percent Change')\n\n    ax6 = plt.subplot(616, sharex=ax1)\n    results[['volume']].plot(ax=ax6)\n    ax6.set_ylabel('Volume (mCoins/5min)')\n\n    plt.legend(loc=3)\n\n    # Show the plot.\n    plt.gcf().set_size_inches(18, 8)\n    plt.show()")

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\IPython\core\interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2101             magic_arg_s = self.var_expand(line, stack_depth)
   2102             with self.builtin_trap:
-> 2103                 result = fn(magic_arg_s, cell)
   2104             return result
   2105 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\__main__.py in catalyst_magic(line, cell)
    324             '%s%%catalyst' % ((cell or '') and '%'),
    325             # don't use system exit and propogate errors to the caller
--> 326             standalone_mode=False,
    327         )
    328     except SystemExit as e:

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\click\core.py in main(self, args, prog_name, complete_var, standalone_mode, **extra)
    695             try:
    696                 with self.make_context(prog_name, args, **extra) as ctx:
--> 697                     rv = self.invoke(ctx)
    698                     if not standalone_mode:
    699                         return rv

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\click\core.py in invoke(self, ctx)
    893         """
    894         if self.callback is not None:
--> 895             return ctx.invoke(self.callback, **ctx.params)
    896 
    897 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\click\core.py in invoke(*args, **kwargs)
    533         with augment_usage_errors(self):
    534             with ctx:
--> 535                 return callback(*args, **kwargs)
    536 
    537     def forward(*args, **kwargs):

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\click\decorators.py in new_func(*args, **kwargs)
     15     """
     16     def new_func(*args, **kwargs):
---> 17         return f(get_current_context(), *args, **kwargs)
     18     return update_wrapper(new_func, f)
     19 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\__main__.py in run(ctx, algofile, algotext, define, data_frequency, capital_base, bundle, bundle_timestamp, start, end, output, print_algo, local_namespace, exchange_name, algo_namespace, base_currency)
    289         simulate_orders=True,
    290         auth_aliases=None,
--> 291         stats_output=None,
    292     )
    293 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\utils\run_algo.py in _run(handle_data, initialize, before_trading_start, analyze, algofile, algotext, defines, data_frequency, capital_base, data, bundle, bundle_timestamp, start, end, output, print_algo, local_namespace, environ, live, exchange, algo_namespace, base_currency, live_graph, analyze_live, simulate_orders, auth_aliases, stats_output)
    206         environ=environ,
    207         exchange_tz='UTC',
--> 208         asset_db_path=None  # We don't need an asset db, we have exchanges
    209     )
    210     env.asset_finder = ExchangeAssetFinder(exchanges=exchanges)

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\finance\trading.py in __init__(self, load, bm_symbol, exchange_tz, trading_calendar, asset_db_path, future_chain_predicates, environ)
     99             trading_calendar.day,
    100             trading_calendar.schedule.index,
--> 101             self.bm_symbol,
    102         )
    103 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\data\loader.py in load_crypto_market_data(trading_day, trading_days, bm_symbol, bundle, bundle_data, environ, exchange, start_dt, end_dt)
    160         field='close',
    161         data_frequency='daily',
--> 162         force_auto_ingest=True)
    163     br.columns = ['close']
    164     br = br.pct_change(1).iloc[1:]

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\exchange\exchange.py in get_history_window_with_bundle(self, assets, end_dt, bar_count, frequency, field, data_frequency, ffill, force_auto_ingest)
    601                 field=field,
    602                 data_frequency=data_frequency,
--> 603                 force_auto_ingest=force_auto_ingest
    604             )
    605 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\exchange\exchange_bundle.py in get_history_window_series_and_load(self, assets, end_dt, bar_count, field, data_frequency, algo_end_dt, force_auto_ingest)
    877                     data_frequency=data_frequency,
    878                     show_progress=True,
--> 879                     show_breakdown=True
    880                 )
    881                 series = self.get_history_window_series(

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\catalyst\exchange\exchange_bundle.py in ingest_assets(self, assets, data_frequency, start_dt, end_dt, show_progress, show_breakdown, show_report)
    607                         exchange=self.exchange_name,
    608                         frequency=data_frequency,
--> 609                         symbol=asset.symbol
    610                     )) as it:
    611                     for chunk in it:

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\click\_termui_impl.py in __enter__(self)
     92     def __enter__(self):
     93         self.entered = True
---> 94         self.render_progress()
     95         return self
     96 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\click\_termui_impl.py in render_progress(self)
    228         if line != self._last_line:
    229             self._last_line = line
--> 230             echo(line, file=self.file, color=self.color, nl=nl)
    231             self.file.flush()
    232 

C:\Users\username\PycharmProjects\firstCatalyst\venv\lib\site-packages\click\utils.py in echo(message, file, nl, err, color)
    257 
    258     if message:
--> 259         file.write(message)
    260     file.flush()
    261 

UnsupportedOperation: not writable

Anyone can assist on this?
Thanks.

**Comment by EmbarAlmog** [comment] 2018-02-28 12:14
Hi kooomix, thanks for reporting. Please run the command 
`catalyst ingest-exchange -x bitfinex -f daily -i btc_usd`  and let me know if you still getting some errors

**Comment by EmbarAlmog** [comment] 2018-02-28 13:49
This issue #179 might be related. Which version of catalyst are you using?

**Comment by kooomix** [comment] 2018-02-28 15:04
version 0.5.3.
I saw the issue you mentioned but didn't really get how should implement the suggested solution there.. moreover, I also get the message "NFO: exchange_bundle: pricing data for ['btc_usd'] not found in range 2015-03-01 00:00:00+00:00 to 2017-06-27 00:00:00+00:00, updating the bundles." which suggest it is actually an issue with the data..

**Comment by EmbarAlmog** [comment] 2018-03-01 10:45
Hi @kooomix I couldn't reproduce this error. I am using also Python 3 and Catalyst 0.5.3. Can you please give me more information about your code? Have you tried to restart Jupyter notebook?

**Comment by kooomix** [comment] 2018-03-04 06:45
Hi,

I'm using the "PyCharm Community Edition 2017.3.3 x64" IDE.
1. I have created a project and then installed catalyst and matplotlib.
2. I have created a Jupiter Notebook file and ran it.
3. Browser opened with my project.
4. I ran the ingest command through the terminal.
5. I ran the notebook and got the stated error.


The code:

**_import matplotlib.pyplot as plt
from catalyst.api import order, record, symbol

# Register the catalyst magic
%load_ext catalyst

# Setup matplotlib to display graphs inline in this Notebook
%matplotlib inline

%%catalyst --start 2015-3-2 --end 2017-6-28 --capital-base 100000 -x bitfinex -c usd

from catalyst.finance.slippage import VolumeShareSlippage

from catalyst.api import (
    order_target_value,
    symbol,
    record,
    cancel_order,
    get_open_orders,
)

def initialize(context):
    context.ASSET_NAME = 'btc_usd'
    context.TARGET_HODL_RATIO = 0.8
    context.RESERVE_RATIO = 1.0 - context.TARGET_HODL_RATIO

    # For all trading pairs in the poloniex bundle, the default denomination
    # currently supported by Catalyst is 1/1000th of a full coin. Use this
    # constant to scale the price of up to that of a full coin if desired.
    context.TICK_SIZE = 1000.0

    context.is_buying = True
    context.asset = symbol(context.ASSET_NAME)

    context.i = 0

def handle_data(context, data):
    context.i += 1

    starting_cash = context.portfolio.starting_cash
    target_hodl_value = context.TARGET_HODL_RATIO * starting_cash
    reserve_value = context.RESERVE_RATIO * starting_cash

    # Cancel any outstanding orders
    orders = get_open_orders(context.asset) or []
    for order in orders:
        cancel_order(order)

    # Stop buying after passing the reserve threshold
    cash = context.portfolio.cash
    if cash <= reserve_value:
        context.is_buying = False

    # Retrieve current asset price from pricing data
    price = data.current(context.asset, 'price')

    # Check if still buying and could (approximately) afford another purchase
    if context.is_buying and cash > price:
        # Place order to make position in asset equal to target_hodl_value
        order_target_value(
            context.asset,
            target_hodl_value,
            limit_price=price*1.1,
        )

    record(
        price=price,
        volume=data.current(context.asset, 'volume'),
        cash=cash,
        starting_cash=context.portfolio.starting_cash,
        leverage=context.account.leverage,
    )

def analyze(context=None, results=None):
    import matplotlib.pyplot as plt

    # Plot the portfolio and asset data.
    ax1 = plt.subplot(611)
    results[['portfolio_value']].plot(ax=ax1)
    ax1.set_ylabel('Portfolio Value (USD)')

    ax2 = plt.subplot(612, sharex=ax1)
    ax2.set_ylabel('{asset} (USD)'.format(asset=context.ASSET_NAME))
    (context.TICK_SIZE * results[['price']]).plot(ax=ax2)

    trans = results.ix[[t != [] for t in results.transactions]]
    buys = trans.ix[
        [t[0]['amount'] > 0 for t in trans.transactions]
    ]
    ax2.plot(
        buys.index,
        context.TICK_SIZE * results.price[buys.index],
        '^',
        markersize=10,
        color='g',
    )

    ax3 = plt.subplot(613, sharex=ax1)
    results[['leverage', 'alpha', 'beta']].plot(ax=ax3)
    ax3.set_ylabel('Leverage ')

    ax4 = plt.subplot(614, sharex=ax1)
    results[['starting_cash', 'cash']].plot(ax=ax4)
    ax4.set_ylabel('Cash (USD)')

    results[[
        'treasury',
        'algorithm',
        'benchmark',
    ]] = results[[
        'treasury_period_return',
        'algorithm_period_return',
        'benchmark_period_return',
    ]]

    ax5 = plt.subplot(615, sharex=ax1)
    results[[
        'treasury',
        'algorithm',
        'benchmark',
    ]].plot(ax=ax5)
    ax5.set_ylabel('Percent Change')

    ax6 = plt.subplot(616, sharex=ax1)
    results[['volume']].plot(ax=ax6)
    ax6.set_ylabel('Volume (mCoins/5min)')

    plt.legend(loc=3)

    # Show the plot.
    plt.gcf().set_size_inches(18, 8)
    plt.show()_**


Thanks.

**Comment by kooomix** [comment] 2018-03-04 09:05
Updating that I have tested the same code using conda (without pycharm) and got the same error so it is probably not related with the pycharm IDE.

**Comment by kooomix** [comment] 2018-03-04 13:31
Another thing that's probably related:
When running the ingest command through the terminal, it looks like data is being properly ingested , but when I ran the same command through the Anaconda Prompt under the catalyst enviroment I get the following message: 
" No such file or directory: 'C:\\Users\\username\\.catalyst\\data\\exchanges\\bitfinex\\daily_bundle\\09\\88\\098871.bcolz\\open\\meta\\storage', trying again"

So I suspect the terminal is writing the data somewhere else that expected by the notebook code... and maybe solving the above error and running the code through the anaconda prompt will solve the issue.

**Comment by EmbarAlmog** [comment] 2018-03-05 10:59
Hi @kooomix please try to uninstall Anaconda and then follow the installation steps while adding it to the path (in the installation of conda). Then install catalyst and jupyter in the terminal and not in the anaconda prompt. Try to ingest your data in the terminal and run jupyter notebook from there.

**Comment by kooomix** [comment] 2018-03-05 11:36
Thanks.
Did you mean to install jupyter through the anaconda prompt and then install catalyst through the jupyter  terminal?

**Comment by EmbarAlmog** [comment] 2018-03-05 12:28
I mean that after installing Anaconda while adding it to the path, you can open CLI (not the anaconda prompt and not the jupyter terminal) and create a new environment there. after creating the environment you can install enigma-catalyst & jupyter & matplotlib using pip and test again the algorithm in jupyter notebook. Good Luck!

**Comment by EmbarAlmog** [comment] 2018-03-15 10:08
Hi @kooomix have you been able to overcome the issues?

**Comment by kooomix** [comment] 2018-03-19 06:37
Hi,

I didn't overcome the issue on my windows so I chose to use linux instead and it works for me now.

Thanks a lot for the help.

**Comment by EmbarAlmog** [comment] 2018-08-05 09:54
Hi @kooomix, I am closing this, if you are still experiencing any issues, feel free to report back and reopen this.

**Closed by EmbarAlmog** 2018-08-05 09:54 UTC
