### ISSUE TITLE
bitfinex live trading - returns ValueError when trying to buy amount higher than 9,999

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#416] opened 2018-07-26 06:40 UTC
Hi,

I'm getting an error when trying to buy more than 9,999 coins in one order.
Error is returns from the call:
_def amount_to_precision(self, symbol, amount):
        return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode)_

In file:
_catalyst/lib/python3.6/site-packages/ccxt/base/decimal_to_precision.py_

After some investigations I figured that the function _decimal_to_precision_ returns ValueError for bitfinex when the amount is at least 5 digits **on the left side of the dot**.

Is it the expected behavior of the precision calculations or is it a bug?

Thanks.

**Comment by lenak25** [comment] 2018-07-26 10:15
Hi @kooomix , it looks like a duplicate of #411

**Comment by lenak25** [comment] 2018-07-26 13:51
After looking at your description once again, the two issues might be connected but different.
Could you please share the exact error you are receiving?

**Comment by kooomix** [comment] 2018-07-26 14:06
This is the relevant traceback:

File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/api_support.py", line 57, in wrapped\n    return getattr(algo_instance, f.__name__)(*args, **kwargs)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/api_support.py", line 126, in wrapped_method\n    return method(self, *args, **kwargs)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 2018, in order_target_percent\n    style=style)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/utils/api_support.py", line 126, in wrapped_method\n    return method(self, *args, **kwargs)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/algorithm.py", line 1463, in order\n    return self.blotter.order(asset, amount, style)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_blotter.py", line 169, in order\n    if amount == 0:\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_blotter.py", line 185, in order\n    args=(asset, amount, style),\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/redo/__init__.py", line 162, in retry\n    return action(*args, **kwargs)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange_blotter.py", line 163, in exchange_order\n    asset, amount, style\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/exchange.py", line 877, in order\n    return self.create_order(asset, amount, is_buy, style)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/catalyst/exchange/ccxt/ccxt_exchange.py", line 899, in create_order\n    price=price\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/ccxt/bitfinex.py", line 549, in create_order\n    amount = self.amount_to_precision(symbol, amount)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/ccxt/bitfinex.py", line 379, in amount_to_precision\n    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol][\'precision\'][\'amount\'], self.precisionMode)\n', '  File "/home/ubuntu/anaconda3/envs/catalyst/lib/python3.6/site-packages/ccxt/base/decimal_to_precision.py", line 74, in decimal_to_precision\n    raise ValueError\n', 'ValueError\n']

It seems like the decimal_to_percision function doesn't work well for SIGNIFICANT_DIGITS and returns error when number of digits on the left of the dot is equal to the "precision" variable.

so for example - if the precision is 5 (as set for bitfinex), for amounts 4567.55 (4 digits left of dot) and 768959.55 (6 digits) it will work, but for amount 67589.45 (exactly 5 digits) it will return the above error.

**Comment by lenak25** [comment] 2018-07-31 11:11
Hi @koomix, 

We are currently working on more urgent issues but hope to get to it in the coming days.
In the meantime, please fell free to submit a pull request if you find a fix for the issue.

Thanks,
Lena

**Comment by kooomix** [comment] 2018-09-03 08:33
Hi @lenak25 
Is there any progress on that issue?

Thanks.

**Comment by AvishaiW** [comment] 2018-11-04 12:43
Hi @kooomix, 
are you still experiencing this issue? seems like the code you mentioned does not exist...
closing this issue, if it's still relevant, please feel free to reopen it.
Thanks!

**Closed by AvishaiW** 2018-11-04 12:43 UTC
