### ISSUE TITLE
pandoc makes pip installation fail

### ISSUE THREAD

**Issue by cryptonoob42** [enigmampc/catalyst#263] opened 2018-03-02 13:56 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Python Version: 2.7.12
* Python Bitness: 64
* How did you install Catalyst: pip
* Python packages: none (fresh venv)

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I am trying to make a fresh install of the latest enigma-catalyst using pip inside a virtual environment. I get the following error:

    Collecting hexbytes<1.0.0,>=0.1.0b1 (from web3>=4.0.0b7->enigma-catalyst)
    Using cached hexbytes-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Maybe try:
    
        sudo apt-get install pandoc
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------
    
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    
    
    !!! pandoc not found, long_description is bad, don't upload this to PyPI !!!
    
    
    
    Installed /tmp/pip-build-EawBUu/hexbytes/.eggs/pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-EawBUu/hexbytes/setup.py", line 67, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/home/rsp/catalyst-venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/rsp/catalyst-venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 333, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/rsp/catalyst-venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 476, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-EawBUu/hexbytes/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-EawBUu/hexbytes/.eggs/pypandoc-1.4-py2.7.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

Just as a side note regarding the line suggesting installation of pandoc via apt: I should have thought that the list of Linux requirements (https://enigma.co/catalyst/install.html#linux) was complete.

BUT: it seems like it's not actually necessary to install pandoc via apt. The error message at the end appears to indicate a different problem.

## Reproduction Steps

1. create venv
2. activate that venv
3. pip install enigma-catalyst

## What steps have you taken to resolve this already?

Tried finding out what the problem is, to no avail ;)

Then, I looked into the Discord support channel and found this note by Lena:

> it is a known issue.. it seems that on some systems the new catalyst version can be installed only with python 3, so we recommend to move to python 3. In any case, we are investigating  this issue in more depth.

So I created a Python3 venv and tried again. That way, installation succeeded. Nonetheless, I would have liked it to succeed with Python 2.

Sincerely,
cryptonoob42

**Comment by lacabra** [comment] 2018-03-02 18:47
Thanks for reporting @cryptonoob42, as you point out this is a known issue, and this is a duplicate of #245, which we haven't yet closed as we are trying to figure out a way around it.

**Comment by lacabra** [comment] 2018-03-02 19:56
This issue has been fixed on branch `develop` on commit 5197ab6cc2ed9df66508b9565f256aebda9258ce. It will be merged onto `master` on our upcoming release early next week.
The Python3 requirement has been isolated to the Data Marketplace, which means that Catalyst continues to support both Python2 and Python3, but if you want to use Catalyst with the Data Marketplace, you need to upgrade your install to Python3 because the primary library that the marketplace uses `web3` has recently dropped support for Python2.

**Closed by lacabra** 2018-03-02 19:56 UTC
Labels: Bug, Res - Duplicate

**Comment by cryptonoob42** [comment] 2018-03-02 20:22
Nice work!

**Comment by nagesh-chowdaiah** [comment] 2020-07-29 20:13
use 'python setup.py download_pandoc' to download pandoc.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help
    
      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for pypandoc
    ERROR: Failed to build one or more wheels
still getting this error

**Comment by nagesh-chowdaiah** [comment] 2020-07-29 20:14
Downloading pyspark-2.4.5.tar.gz (217.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.7.8/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g6zf6_ia/pyspark/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g6zf6_ia/pyspark/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-lnbjuppu
         cwd: /tmp/pip-install-g6zf6_ia/pyspark/
    Complete output (47 lines):
    Could not import pypandoc - required to package PySpark
    WARNING: The wheel package is not available.
      ERROR: Command errored out with exit status 1:
       command: /opt/hostedtoolcache/Python/3.7.8/x64/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-7kmuwvv7/pypandoc/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-7kmuwvv7/pypandoc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mqtwedy3
           cwd: /tmp/pip-wheel-7kmuwvv7/pypandoc/
      Complete output (8 lines):
      no pandoc found, building platform unspecific wheel...
      use 'python setup.py download_pandoc' to download pandoc.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]

Still getting this error

**Comment by gozes** [comment] 2021-03-22 11:40
yup still seeing this error as well
