### ISSUE TITLE
ImportError: cannot import name 'RLock'

### ISSUE THREAD

**Issue by thezoug** [enigmampc/catalyst#458] opened 2018-09-07 18:24 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: Windows 10
* Python Version: Python 3.6
* Python Bitness: 
* How did you install Catalyst: conda
* Python packages: conda, catalyst

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
when importing catalyst, I encounter this error :
`
ImportError: cannot import name 'RLock'`
* What did you expect to happen?
expected the class to be imported
* What happened instead?
this disaster...

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-d6b2d908c459> in <module>()
----> 1 from catalyst.api import order, record

~\AppData\Roaming\Python\Python36\site-packages\catalyst\__init__.py in <module>()
     18 # This is *not* a place to dump arbitrary classes/modules for convenience,
     19 # it is a place to expose the public interfaces.
---> 20 from . import data
     21 from . import finance
     22 from . import gens

~\AppData\Roaming\Python\Python36\site-packages\catalyst\data\__init__.py in <module>()
----> 1 from . import loader
      2 from .loader import (
      3     load_from_yahoo,
      4     load_bars_from_yahoo,
      5     load_prices_from_csv,

~\AppData\Roaming\Python\Python36\site-packages\catalyst\data\loader.py in <module>()
     16 from collections import OrderedDict
     17 
---> 18 import logbook
     19 import pandas as pd
     20 import pytz

~\Anaconda3\lib\site-packages\logbook\__init__.py in <module>()
     12 
     13 import os
---> 14 from .base import (
     15     LogRecord, Logger, LoggerGroup, NestedSetup,  Processor, Flags,
     16     get_level_name, lookup_level, dispatch_record, CRITICAL, ERROR, WARNING,

~\Anaconda3\lib\site-packages\logbook\base.py in <module>()
     15 from weakref import ref as weakref
     16 from datetime import datetime
---> 17 from logbook.concurrency import (
     18     thread_get_name, thread_get_ident, greenlet_get_ident)
     19 

~\Anaconda3\lib\site-packages\logbook\concurrency.py in <module>()
     29 
     30 if has_gevent:
---> 31     from gevent._threading import (Lock as ThreadLock,
     32                                    RLock as ThreadRLock,
     33                                    get_ident as thread_get_ident,

ImportError: cannot import name 'RLock'
```

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. `from catalyst.api import order, record`
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,

**Comment by treethought** [comment] 2018-09-07 22:13
looks like a duplicate of #456

**Comment by lenak25** [comment] 2018-09-12 13:13
@treethought I agree, thanks, I closing this. 
@thezoug if you are not using the `gevent` library - meaning that this issue has a different origin - please reopen and share more details.

Thanks,
Lena

**Closed by lenak25** 2018-09-12 13:13 UTC
