### ISSUE TITLE
Error:catalyst.exchange.exchange_errors.ExchangeAuthEmpty: Please enter your API token key and secret for exchange Binance in the following file: C:\Users\ASUS\.catalyst\data\exchanges\binance\auth.json

### ISSUE THREAD

**Issue by wkpzwy** [enigmampc/catalyst#474] opened 2018-09-20 04:29 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1.
2.
3.
...

## What steps have you taken to resolve this already?

...

# Anything else?

...

Sincerely,
`$ whoami`

**Comment by lenak25** [comment] 2018-09-20 09:58
This is a duplicate of #473

**Closed by lenak25** 2018-09-20 09:58 UTC
Labels: Res - Duplicate
