### ISSUE TITLE
Data.history "volume" inconsistency among different exchanges

### ISSUE THREAD

**Issue by kooomix** [enigmampc/catalyst#463] opened 2018-09-13 06:09 UTC
Hi,

I suspect the "volume" returned for binance and poloniex (As examples) is different. 
If we try to get volumes for "eth_btc" as an example, in poloniex it will return the volume in BTC while in binance it will return the volume of ETH.

Besides the fact it behave differently, it mainly causes problems when requesting volumes for multiple coins, which them requires additional data manipulation in order to unify volume data.

**Comment by lenak25** [comment] 2018-09-13 07:55
Hi @kooomix , this is a duplicate of #427 , please refer to that thread.

Thanks,

Lenae

**Closed by lenak25** 2018-09-13 07:55 UTC
Labels: Res - Duplicate
