### ISSUE TITLE
info: exchange_blotter: order has not reached the trigger at current price

### ISSUE THREAD

**Issue by demontamer** [enigmampc/catalyst#211] opened 2018-02-06 03:56 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: ubuntu 14.04
* Python Version: `2.7`
* Python Bitness: ``
* How did you install Catalyst:`pip`
* Python packages: `$ pip freeze` 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
During backtest I noticed a lot of my buy orders are not executing and catalyst logs ` ...order has not reached the trigger at current price`. I suspect this is to do with my limit orders but I can't seem to get rid of it.  Can you explain this behavior and how to set my orders up so they execute?
* What did you expect to happen?
Orders execute
* What happened instead?

catalyst issues above warning and never executes the orders

Here is how you can reproduce this issue on your machine:
I have not idea what's the cause so can't tell you how to accurately reproduce other than:

## Reproduction Steps

1. select a pair on bitterex
2. run a backtest over a period of time
3. use  `order_target_percent(asset=asset, 
                                     target=1,
                                     limit_price=price * 1.05)`
...

## What steps have you taken to resolve this already?

increased limit_price

...

# Anything else?

...

Sincerely,
`demontamer`

**Comment by fredfortier** [comment] 2018-02-06 04:29
I believe that this is a duplicate of #183. We fixed in the develop branch but did not release yet. We'll release in the next day or two.

**Comment by fredfortier** [comment] 2018-02-07 04:34
We're releasing this tomorrow.

**Comment by fredfortier** [comment] 2018-02-09 05:05
In release 0.5.2

**Closed by fredfortier** 2018-02-09 05:05 UTC
Labels: Bug, Res - Fixed
