### ISSUE TITLE
Error running example "buy_btc_simple"

### ISSUE THREAD

**Issue by ielashi** [enigmampc/catalyst#104] opened 2017-12-17 17:22 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: macOS 10.13.1
* Python Version: Python 3.6.3
* Python Bitness: 64
* How did you install Catalyst: pip
* Python packages:

aiodns==1.1.1
aiohttp==2.3.6
alembic==0.9.6
apipkg==1.4
appnope==0.1.0
asn1crypto==0.24.0
async-timeout==2.0.0
atari-py==0.1.1
bcolz==0.12.1
bitfinex==0.2.6
bittrex==0.1.4
bleach==1.5.0
boto3==1.5.1
botocore==1.8.15
Bottleneck==1.2.1
btfxwss==1.1.14
cchardet==2.1.1
ccxt==1.10.393
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
click==6.7
codacy-coverage==1.3.9
contextlib2==0.5.5
coverage==4.4.2
cryptocompare==0.3
cryptography==2.1.4
cvxopt==1.1.9
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
decorator==4.1.2
docutils==0.14
empyrical==0.2.1
enigma-catalyst==0.4.0
entrypoints==0.2.3
enum34==1.1.6
execnet==1.5.0
future==0.16.0
Glances==2.11.1
gym==0.9.4
h5py==2.7.1
html5lib==0.9999999
httpretty==0.8.14
idna==2.6
intervaltree==2.1.0
ipdb==0.10.3
ipykernel==4.6.1
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.0.4
jedi==0.11.0
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
Keras==1.2.2
keras-rl==0.3.1
knapsack==0.0.3
Logbook==1.1.0
lru-dict==1.1.6
Mako==1.0.7
Markdown==2.6.9
MarkupSafe==1.0
matplotlib==1.4.3
mem-top==0.1.5
mistune==0.8.1
multidict==3.3.2
multipledispatch==0.4.9
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
nose==1.3.7
notebook==5.2.1
numexpr==2.6.4
numpy==1.13.3
olefile==0.44
pachi-py==0.0.21
pandas==0.19.2
pandas-datareader==0.5.0
pandocfilters==1.4.2
parso==0.1.0
patsy==0.4.1
pexpect==4.3.0
pickleshare==0.7.4
Pillow==4.3.0
prompt-toolkit==1.0.15
protobuf==3.5.0
psutil==5.4.1
ptyprocess==0.5.2
py==1.5.2
PyAlgoTrade==0.18
pycares==2.3.0
pycparser==2.18
pyglet==1.3.0
Pygments==2.2.0
Pympler==0.5
PyOpenGL==3.1.0
pyparsing==2.2.0
PyScaffold==2.5.8
pytest==3.2.5
pytest-cov==2.5.1
pytest-forked==0.2
pytest-xdist==1.20.1
python-bittrex==0.2.1
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2017.3
PyYAML==3.12
pyzmq==16.0.3
qtconsole==4.3.1
raven==6.3.0
requests==2.18.4
requests-file==1.4.2
requests-ftp==0.3.1
s3transfer==0.1.12
schedule==0.5.0
scipy==1.0.0
seaborn==0.8.1
simplegeneric==0.8.1
six==1.11.0
slackclient==1.1.0
sortedcontainers==1.5.9
SQLAlchemy==1.1.15
statsmodels==0.8.0
TA-Lib==0.4.10
tables==3.4.2
tensorflow==1.4.0
tensorflow-tensorboard==0.4.0rc3
terminado==0.6
testpath==0.3.1
tflearn==0.3.2
Theano==0.9.0
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.44.0
websockets==4.0.1
Werkzeug==0.12.2
widgetsnbextension==3.0.7
yarl==0.16.0
zipline-poloniex==0.1.2

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I am failing to run the example "buy_btc_simple" that's included with catalyst.

```
> python buy_btc_simple.py
[2017-12-17 17:20:59.612552] INFO: run_algo: running algo in paper-trading mode
[2017-12-17 17:21:07.698097] WARNING: Loader: Refusing to download new treasury data because a download succeeded at 2017-12-17 16:49:15.319350+00:00.
[2017-12-17 17:21:07.700107] INFO: exchange_algorithm: initialized trading algorithm in backtest mode
Traceback (most recent call last):
  File "buy_btc_simple.py", line 48, in <module>
    end=pd.to_datetime('2017-10-31', utc=True),
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 563, in run_algorithm
    stats_output=stats_output
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/utils/run_algo.py", line 346, in _run
    overwrite_sim_params=False,
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/exchange/exchange_algorithm.py", line 318, in run
    data, overwrite_sim_params
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/algorithm.py", line 724, in run
    for perf in self.get_generator():
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 224, in transform
    for capital_change_packet in every_bar(dt):
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/gens/tradesimulation.py", line 122, in every_bar
    blotter.get_transactions(current_data)
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/exchange/exchange_blotter.py", line 294, in get_transactions
    return super(ExchangeBlotter, self).get_transactions(bar_data)
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/finance/blotter.py", line 371, in get_transactions
    additional_commission = commission.calculate(order, txn)
  File "/Users/ielashi/dev/reinforcement-learning/rl/lib/python3.6/site-packages/catalyst/exchange/exchange_blotter.py", line 64, in calculate
    if ((order.amount > 0 and order.limit < transaction.price)
TypeError: '<' not supported between instances of 'NoneType' and 'float'```

**Comment by inevity** [comment] 2017-12-19 14:26
For marketorder,order.limit == none,so when calc the commission, need consider the style.

**Comment by inevity** [comment] 2017-12-19 14:54
When change the example buy_btc_simple order as     order(context.asset, 1, limit_price=1000),  pass.
Now the issue is that How  should the commission calc by TradingPairFeeSchedule.calculate()!

**Comment by fredfortier** [comment] 2017-12-19 17:08
Thanks for the pull request. We will take a look and merge shortly.

**Comment by fredfortier** [comment] 2018-01-04 03:45
Merged the pull request. I understand that this fixed. Please let me know if I'm missing something.

**Closed** 2018-01-04 21:30 UTC
Labels: Bug, Res - Fixed
