### ISSUE TITLE
_tkinter.TclError: no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by DASHsekar** [enigmampc/catalyst#231] opened 2018-02-13 08:14 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
* Python Version: `$ python --version`
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
* Python packages: `$ pip freeze` or `$ conda list`

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

i'm running mininet/examples/miniedit.py in MIninet
i received this issue.

MiniEdit running against Mininet 2.2.2
Traceback (most recent call last):
  File "mininet/examples/miniedit.py", line 3579, in <module>
    app = MiniEdit()
  File "mininet/examples/miniedit.py", line 1110, in __init__
    Frame.__init__( self, parent )
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2537, in __init__
    Widget.__init__(self, master, 'frame', cnf, {}, extra)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2049, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2024, in _setup
    _default_root = Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

Sincerely,
`sekar

**Comment by lacabra** [comment] 2018-02-13 17:16
Duplicate of #39, where this is resolved. It is also covered in our documentation here:
https://enigmampc.github.io/catalyst/install.html#macos-virtualenv-conda-matplotlib

**Closed by lacabra** 2018-02-13 17:16 UTC
