### ISSUE TITLE
pip upgrade failed for enigma-catalyst

### ISSUE THREAD

**Issue by vivekbasappa** [enigmampc/catalyst#246] opened 2018-02-23 03:41 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`)
{code}
Linux ubuntu 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
{code}
* Python Version: `$ python --version`
Python 2.7.12

* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
64
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`)
pip
* Python packages: `$ pip freeze` or `$ conda list`
{code}
xxxx@ubuntu:~$ pip freeze
absl-py==0.1.10
adium-theme-ubuntu==0.3.4
alembic==0.9.8
attrdict==2.0.0
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0.post1
bcolz==0.12.1
bleach==2.1.2
boto3==1.5.31
botocore==1.8.45
Bottleneck==1.2.1
ccxt==1.10.1152
certifi==2018.1.18
chardet==3.0.4
click==6.7
configparser==3.5.0
contextlib2==0.5.5
CVXcanon==0.1.1
cvxopt==1.1.9
cvxpy==0.4.11
cycler==0.10.0
cyordereddict==1.0.0
Cython==0.27.3
cytoolz==0.9.0
decorator==4.2.1
dill==0.2.7.1
docutils==0.14
ecos==2.0.5
empyrical==0.2.1
enigma-catalyst==0.5.3
entrypoints==0.2.3
enum34==1.1.6
eth-abi==1.0.0b0
eth-account==0.1.0a2
eth-keyfile==0.5.1
eth-keys==0.2.0b1
eth-rlp==0.1.0a2
eth-utils==1.0.0b1
fastcache==1.0.2
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.2.0
h5py==2.7.1
hexbytes==0.1.0b0
html5lib==1.0.1
idna==2.6
influxdb==5.0.0
intervaltree==2.1.0
ipykernel==4.8.1
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.1.2
Jinja2==2.10
jmespath==0.9.3
joblib==0.11
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
Logbook==1.2.1
lru-dict==1.1.6
lxml==4.1.1
Mako==1.0.7
Markdown==2.6.11
MarkupSafe==1.0
matplotlib==2.1.2
mistune==0.8.3
mock==2.0.0
multipledispatch==0.4.9
multiprocess==0.70.5
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
notebook==5.4.0
numexpr==2.6.4
numpy==1.14.0
pandas==0.19.2
pandas-datareader==0.6.0
pandocfilters==1.4.2
pathlib2==2.3.0
patsy==0.5.0
pbr==3.1.1
pexpect==4.4.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
protobuf==3.5.1
ptyprocess==0.5.2
pycryptodome==3.4.11
pyfolio==0.8.0
Pygments==2.2.0
pykalman==0.9.5
pymc3==3.3
pyparsing==2.2.0
pysha3==1.0.2
python-dateutil==2.6.1
python-editor==1.0.3
pytz==2018.3
PyYAML==3.12
pyzmq==17.0.0
qtconsole==4.3.1
redo==1.6
requests==2.18.4
requests-file==1.4.3
requests-ftp==0.3.1
requests-toolbelt==0.8.0
rlp==0.6.0
s3transfer==0.1.13
scandir==1.7
scikit-learn==0.19.1
scipy==1.0.0
scs==2.0.2
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
sortedcontainers==1.5.9
SQLAlchemy==1.2.3
statsmodels==0.8.0
subprocess32==3.2.7
TA-Lib==0.4.16
tables==3.4.2
tensorflow==1.5.0
tensorflow-tensorboard==1.5.1
terminado==0.8.1
testpath==0.3.1
Theano==1.0.1
toolz==0.9.0
tornado==4.5.3
tqdm==4.19.5
traitlets==4.3.2
unity-lens-photos==1.0
urllib3==1.22
wcwidth==0.1.7
web3==4.0.0b9
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.1.4
wrapt==1.10.11
{code}
Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue
pip upgrade failed for enigma-catalyst
{code}
xxxx@ubuntu:~$ sudo  sudo apt-get install pandoc
[sudo] password for vivek:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  liblua5.1-0 libluajit-5.1-2 libluajit-5.1-common pandoc-data
Suggested packages:
  texlive-latex-recommended texlive-xetex texlive-luatex pandoc-citeproc etoolbox wkhtmltopdf
The following NEW packages will be installed:
  liblua5.1-0 libluajit-5.1-2 libluajit-5.1-common pandoc pandoc-data
0 upgraded, 5 newly installed, 0 to remove and 111 not upgraded.
Need to get 7,028 kB of archives.
After this operation, 55.2 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 liblua5.1-0 amd64 5.1.5-8ubuntu1 [102 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 libluajit-5.1-common all 2.0.4+dfsg-1 [35.3 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 libluajit-5.1-2 amd64 2.0.4+dfsg-1 [205 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 pandoc-data all 1.16.0.2~dfsg-1 [84.0 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 pandoc amd64 1.16.0.2~dfsg-1 [6,601 kB]
Fetched 7,028 kB in 1s (4,431 kB/s)
Selecting previously unselected package liblua5.1-0:amd64.
(Reading database ... 179049 files and directories currently installed.)
Preparing to unpack .../liblua5.1-0_5.1.5-8ubuntu1_amd64.deb ...
Unpacking liblua5.1-0:amd64 (5.1.5-8ubuntu1) ...
Selecting previously unselected package libluajit-5.1-common.
Preparing to unpack .../libluajit-5.1-common_2.0.4+dfsg-1_all.deb ...
Unpacking libluajit-5.1-common (2.0.4+dfsg-1) ...
Selecting previously unselected package libluajit-5.1-2:amd64.
Preparing to unpack .../libluajit-5.1-2_2.0.4+dfsg-1_amd64.deb ...
Unpacking libluajit-5.1-2:amd64 (2.0.4+dfsg-1) ...
Selecting previously unselected package pandoc-data.
Preparing to unpack .../pandoc-data_1.16.0.2~dfsg-1_all.deb ...
Unpacking pandoc-data (1.16.0.2~dfsg-1) ...
Selecting previously unselected package pandoc.
Preparing to unpack .../pandoc_1.16.0.2~dfsg-1_amd64.deb ...
Unpacking pandoc (1.16.0.2~dfsg-1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up liblua5.1-0:amd64 (5.1.5-8ubuntu1) ...
Setting up libluajit-5.1-common (2.0.4+dfsg-1) ...
Setting up libluajit-5.1-2:amd64 (2.0.4+dfsg-1) ...
Setting up pandoc-data (1.16.0.2~dfsg-1) ...
Setting up pandoc (1.16.0.2~dfsg-1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
vivek@ubuntu:~$ pip install --upgrade enigma-catalyst  --user
Requirement already up-to-date: enigma-catalyst in ./.local/lib/python2.7/site-packages
Requirement already up-to-date: tables>=3.3.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: python-dateutil>=2.4.2 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: statsmodels>=0.6.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Collecting ccxt>=1.10.1049 (from enigma-catalyst)
  Using cached ccxt-1.10.1185-py2.py3-none-any.whl
Requirement already up-to-date: redo>=1.6 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: patsy>=0.4.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Collecting web3>=4.0.0b7 (from enigma-catalyst)
  Using cached web3-4.0.0b10.tar.gz
Requirement already up-to-date: setuptools>36.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: contextlib2>=0.4.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Collecting sqlalchemy>=1.0.8 (from enigma-catalyst)
  Using cached SQLAlchemy-1.2.4.tar.gz
Requirement already up-to-date: scipy>=0.17.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: numexpr>=2.6.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: six>=1.10.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: empyrical<0.2.2,>=0.2.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: MarkupSafe>=0.23 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: bcolz<1,>=0.12.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Collecting boto3>=1.4.8 (from enigma-catalyst)
  Using cached boto3-1.5.35-py2.py3-none-any.whl
Requirement already up-to-date: lru-dict>=1.1.4 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: bottleneck>=1.0.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: pandas<0.20,>=0.19.2 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: Cython>=0.25.2 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: decorator>=4.0.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Collecting numpy>=1.13.1 (from enigma-catalyst)
  Using cached numpy-1.14.1-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already up-to-date: cyordereddict>=0.2.2 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: requests-file>=1.4.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: Mako>=1.0.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: click>=4.0.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: requests>=2.9.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: toolz>=0.8.2 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: requests-toolbelt>=0.8.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: sortedcontainers>=1.4.4 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: multipledispatch>=0.4.8 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: pip>=7.1.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: alembic>=0.7.7 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: intervaltree>=2.1.0 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: networkx>=1.9.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: Logbook>=0.12.5 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: pandas-datareader>=0.2.1 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: pytz>=2016.4 in ./.local/lib/python2.7/site-packages (from enigma-catalyst)
Requirement already up-to-date: certifi==2018.1.18 in ./.local/lib/python2.7/site-packages (from ccxt>=1.10.1049->enigma-catalyst)
Requirement already up-to-date: cytoolz<1.0.0,>=0.9.0 in ./.local/lib/python2.7/site-packages (from web3>=4.0.0b7->enigma-catalyst)
Collecting eth-abi<2,>=1.0.0-beta.1 (from web3>=4.0.0b7->enigma-catalyst)
  Using cached eth-abi-1.0.0b1.tar.gz
Requirement already up-to-date: eth-account<1.0.0,>=0.1.0a2 in ./.local/lib/python2.7/site-packages (from web3>=4.0.0b7->enigma-catalyst)
Collecting eth-utils<2.0.0,>=1.0.0b1 (from web3>=4.0.0b7->enigma-catalyst)
  Using cached eth-utils-1.0.0b2.tar.gz
Collecting hexbytes<1.0.0,>=0.1.0b1 (from web3>=4.0.0b7->enigma-catalyst)
  Using cached hexbytes-0.1.0b1.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__

    Installed /tmp/pip-build-hPqhxe/hexbytes/.eggs/pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hPqhxe/hexbytes/setup.py", line 67, in <module>
        'Programming Language :: Python :: Implementation :: PyPy',
      File "/home/vivek/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/vivek/.local/lib/python2.7/site-packages/setuptools/dist.py", line 333, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/vivek/.local/lib/python2.7/site-packages/setuptools/dist.py", line 476, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-hPqhxe/hexbytes/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/tmp/pip-build-hPqhxe/hexbytes/.eggs/pypandoc-1.4-py2.7.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hPqhxe/hexbytes/
{code}
* What did you expect to happen?
upgrade should be successful
* What happened instead?
failed with error
Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. pip install --upgrade enigma-catalyst
2.
3.
...

## What steps have you taken to resolve this already?
nothing has been done , waiting for your response
...

# Anything else?

...

Sincerely,
Vivek

**Comment by lacabra** [comment] 2018-02-23 04:45
Duplicate of #245. Closing this one in favor of the former.

**Closed by lacabra** 2018-02-23 04:45 UTC
