### ISSUE TITLE
cancel_order does not work anymore with Binance in Live Trading mode

### ISSUE THREAD

**Issue by cnt285** [enigmampc/catalyst#418] opened 2018-07-26 17:25 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System: (Windows Version or `$ uname --all`) Ubuntu 16
* Python Version: python 3.6
* Python Bitness: `$ python -c 'import math, sys;print(int(math.log(sys.maxsize + 1, 2) + 1))'`
* How did you install Catalyst: (`pip`, `conda`, or `other (please explain)`) virtualenv

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

I have just upgraded to Catalyst 0.5.18. I am testing cancel_order with Binance in Live trading mode. I have a key error with this version:   
   1138         if not self.simulate_orders:
-> 1139             exchange_name = self.blotter.orders[order_id].asset.exchange
   1140             exchange = self.exchanges[exchange_name]
   1141             retry(

KeyError: '67868981'
.  I think order_id type may be integer? or maybe the type issue. Note that the order_id exists in the system. Thanks.

* What did you expect to happen? 
Order should be cancelled in Binance.

Sincerely,
Henry

**Comment by AvishaiW** [comment] 2018-07-27 15:03
Hi, I tried to reproduce this issue, but in all attempts, I was able to cancel the order. with which arguments did you run the method? where did you take the order_id from? can you please elaborate? Thanks!

**Comment by FrankWangTrading** [comment] 2018-07-31 16:30
@cnt285 @AvishaiW i ran into the same / similar issue. When live trading was killed and relaunched while orders are working on Binance, the cancel _order will fail. (catalyst version 0.5.18) 

```
cur_orders = get_open_orders(asset) if is_live else context.blotter.open_orders[context.asset]
for o in cur_orders:
            if asset.exchange == 'binance':
                cancel_order(o, symbol = asset)
            else:
                cancel_order(o)
```
Output:
line 1139, in cancel_order
    exchange_name = self.blotter.orders[order_id].asset.exchange
KeyError: '2129615'

Hope that can help you reproduct the issue @AvishaiW

**Comment by EmbarAlmog** [comment] 2018-08-28 08:59
@FWangTrading , thank you for reporting. If you opened an order and then your algorithm was killed, the order is not saved for the next run. Saving the state of the open orders between runs is not yet supported but an important enhancement, which deserves its own ticket. Could you please open a new issue describing this?

@cnt285 , I'm closing this issue due to low activity, if you still experience this problem please reopen it and add additional information. 
Thanks!

**Closed by EmbarAlmog** 2018-08-28 08:59 UTC
Labels: Help Wanted
