### ISSUE TITLE
403 on https://poloniex.com/public?command=returnTicker

### ISSUE THREAD

**Issue by Alishankhan** [enigmampc/catalyst#163] opened 2018-01-13 20:37 UTC
Dear Catalyst Maintainers,

Before I tell you about my issue, let me describe my environment:

# Environment

* Operating System:Linux  4.9.0-deepin13-amd64 #1 SMP PREEMPT Deepin 4.9.57-1 (2017-10-19) x86_64 GNU/Linux
* Python Version: Python 2.7.14 :: Anaconda, Inc.
* Python Bitness: 64
* How did you install Catalyst: pip 
* Python packages:
# packages in environment at /home/mohd/anaconda3/envs/catalyst:
#
alembic                   0.9.6                     <pip>
backports.functools-lru-cache 1.4                       <pip>
bcolz                     0.12.1                    <pip>
boto3                     1.5.14                    <pip>
botocore                  1.8.28                    <pip>
Bottleneck                1.2.1                     <pip>
ca-certificates           2017.08.26           h1d4fec5_0  
ccxt                      1.10.686                  <pip>
certifi                   2017.11.5        py27h71e7faf_0  
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
contextlib2               0.5.5                     <pip>
cycler                    0.10.0                    <pip>
cyordereddict             1.0.0                     <pip>
Cython                    0.27.3                    <pip>
decorator                 4.1.2                     <pip>
docutils                  0.14                      <pip>
empyrical                 0.2.1                     <pip>
enigma-catalyst           0.4.4                     <pip>
future                    0.16.0                    <pip>
futures                   3.2.0                     <pip>
idna                      2.6                       <pip>
intel-openmp              2018.0.0             hc7b2577_8  
intervaltree              2.1.0                     <pip>
jmespath                  0.9.3                     <pip>
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran-ng            7.2.0                h9f7466a_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
Logbook                   1.1.0                     <pip>
lru-dict                  1.1.6                     <pip>
Mako                      1.0.7                     <pip>
MarkupSafe                1.0                       <pip>
matplotlib                2.1.1                     <pip>
mkl                       2018.0.1             h19d6760_4  
multipledispatch          0.4.9                     <pip>
ncurses                   6.0                  h9df7e31_2  
networkx                  2.0                       <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0           py27h3dfced4_0  
openssl                   1.0.2n               hb7f436b_0  
pandas                    0.19.2                    <pip>
pandas-datareader         0.5.0                     <pip>
patsy                     0.5.0                     <pip>
pip                       9.0.1            py27ha730c48_4  
pyparsing                 2.2.0                     <pip>
python                    2.7.14              h1571d57_29  
python-dateutil           2.6.1                     <pip>
python-editor             1.0.3                     <pip>
pytz                      2017.3                    <pip>
readline                  7.0                  ha6073c6_4  
redo                      1.6                       <pip>
requests                  2.18.4                    <pip>
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
s3transfer                0.1.12                    <pip>
scipy                     1.0.0            py27hf5f0f52_0  
setuptools                38.4.0                   py27_0  
six                       1.11.0                    <pip>
sortedcontainers          1.5.9                     <pip>
SQLAlchemy                1.2.0                     <pip>
sqlite                    3.20.1               hb898158_2  
statsmodels               0.8.0                     <pip>
subprocess32              3.2.7                     <pip>
tables                    3.4.2                     <pip>
tk                        8.6.7                hc745277_3  
toolz                     0.9.0                     <pip>
urllib3                   1.22                      <pip>
wheel                     0.30.0           py27h2bc6bb2_1  
zlib                      1.2.11               ha838bed_2 

Now that you know a little about me, let me tell you about the issue I am
having:

# Description of Issue

* What did you expect to happen?
* What happened instead?

Here is how you can reproduce this issue on your machine:

## Reproduction Steps

1. run command 
catalyst run -f buy_btc_simple.py -x bitfinex --start 2016-1-1 --end 2017-9-30 -c usd --capital-base 100000 -o buy_btc_simple_out.pickle

2. command ended with 403 error on poloniex https://poloniex.com/public?command=returnTicker 

...

## What steps have you taken to resolve this already?

Directly hit above url using firefox developer edition(58) and it works. 

Sincerely,
Alishan

**Comment by lacabra** [comment] 2018-01-14 03:20
Thanks @Alishankhan for reporting this issue. This is a duplicate of #161.

**Closed by lacabra** 2018-01-14 03:21 UTC

**Comment by Alishankhan** [comment] 2018-01-14 04:00
@lacabra  even running statergy on bittrex, script hit poloniex first and result in 404 error
I'm doing something wrong?

**Comment by lacabra** [comment] 2018-01-25 16:58
@Alishankhan This has been fixed in version 0.4.6. Please upgrade and the error will go away.
